### ISSUE TITLE
Missing images in documents

### ISSUE THREAD

**Issue by alexander-mironov** [Aohayou/MaterialValues#2]
Documents in docs/component have some images missing. The problem is with using relative path "../../images/" instead of correct "../images".

**Comment by esnaultdev** [comment]
Should be working now.

What browser are you using?
Both Chromium Version 53.0.2785.143 and Chrome Mobile Version 54.0.2840.68 displayed the images without problem.

Local documentation using `mkdocs serve` now has an incorrect path for images, I will have to dig into that.

**Comment by alexander-mironov** [comment]
Chrome 54.0.2840.71, Mobile Chrome 54.0.2840.68 and Microsoft Edge 38.14393.0.0

Still doesn't work

**Comment by esnaultdev** [comment]
Can you link me the src of an image not being displayed?

I switched from "../../images/" to "/MaterialValues/images", which should work.

**Comment by alexander-mironov** [comment]
For examples: https://github.com/AoDevBlue/MaterialValues/raw/master/MaterialValues/images/components_bottomnavigation_spec_fixed2.png

**Comment by esnaultdev** [comment]
Oh, I see!
The docs/ folder is only used to generate the documentation available [here](https://aodevblue.github.io/MaterialValues/).

Thank you for the information, I added a disclaimer here.

**Comment by alexander-mironov** [comment]
Thank you for a clarification.
